apiVersion: v1
kind: Pod
metadata:
  name: printenv
  namespace: my-ns
  labels:
    purpose: execute-command
spec:
  containers:
  - name: printenv-container
    image: ubuntu
    command: ["printenv"]
  restartPolicy: OnFailure